CREATE TABLE TEAM(
	TeamName VARCHAR(30) NOT NULL,
	City VARCHAR(30) NOT NULL,
	PhoneNo VARCHAR(15) NOT NULL UNIQUE,
	CONSTRAINT TEAMPK
	  PRIMARY KEY (TeamName)
	
);

CREATE TABLE PLAYER(
	PlayerID CHAR(6) NOT NULL,
	PlayerName VARCHAR(30) NOT NULL,
	PlayerDOB DATE NOT NULL,
	PlayerNationality VARCHAR(30) NOT NULL,
	PlayerTeam VARCHAR(30),
	KitNo INT NOT NULL,
	UNIQUE(KitNo,PlayerTeam),
	CONSTRAINT PPK
	  PRIMARY KEY (PlayerID), 
	CONSTRAINT PFK
	  FOREIGN KEY (PlayerTeam) REFERENCES TEAM(TeamName)
	  		ON DELETE SET NULL   ON UPDATE CASCADE,
	 CHECK(1<=KitNo AND KitNo<=99)
);

CREATE TABLE PLAYER_STAT(
	PlayerID CHAR(6) NOT NULL,
	PlayerPosition VARCHAR(5) NOT NULL,
	Appearances INT DEFAULT 0,
	GoalsScored INT DEFAULT 0,
	RedCards INT DEFAULT 0,
	YellowCards INT DEFAULT 0,
	Suspensions INT DEFAULT 0,
	CONSTRAINT PSPK
	  PRIMARY KEY (PlayerID), 
	CONSTRAINT PSFK
	  FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID)
	  		ON DELETE CASCADE   ON UPDATE CASCADE,
	CHECK(GoalsScored>=0)
);

CREATE TABLE TEAM_STAT(
	TeamName VARCHAR(30) NOT NULL,
	Wins INT NOT NULL,
	Draws INT NOT NULL,
	Losses INT NOT NULL,
	GoalDiff INT DEFAULT 0,
	Points 	INT NOT NULL,
	LeaguePosition INT NOT NULL UNIQUE,
	CONSTRAINT TSPK
	  PRIMARY KEY(TeamName),
	CONSTRAINT TSFK
	  FOREIGN KEY(TeamName) REFERENCES TEAM(TeamName)
	  		ON DELETE CASCADE 	ON UPDATE CASCADE,
	CHECK(1<=LeaguePosition<=20)

);

CREATE TABLE STADIUM(
	StadiumName VARCHAR(15) NOT NULL,
	Team VARCHAR(15) NOT NULL UNIQUE,
	Address VARCHAR(50) NOT NULL UNIQUE,
	Capacity INT DEFAULT 40000,
	Turftype VARCHAR(10) NOT NULL,
	FifaCertification CHAR(1) NOT NULL,
	CONSTRAINT SPK
		PRIMARY KEY(StadiumName),
	CONSTRAINT SFK
	FOREIGN KEY(Team) REFERENCES TEAM(TeamName)
			ON DELETE CASCADE	ON UPDATE CASCADE
);

CREATE TABLE MANAGER(
	ManagerName VARCHAR(30) NOT NULL,
	MgrTeam VARCHAR(30) NOT NULL UNIQUE,
	CoachingLicenseNo char(6) NOT NULL,
	MgrDOB DATE NOT NULL,
	MgrNationality VARCHAR(30) NOT NULL,
	CONSTRAINT MGRPK
		PRIMARY KEY(CoachingLicenseNo),
	CONSTRAINT MGRFK
	FOREIGN KEY(MgrTeam) REFERENCES TEAM(TeamName)
			ON DELETE CASCADE	ON UPDATE CASCADE 	

);

CREATE TABLE REFEREE(
	RefereeName VARCHAR(30) NOT NULL,
	RefereeLicenseNo char(6) NOT NULL,
	RefDOB DATE NOT NULL,
	RefNationality VARCHAR(30) NOT NULL,
	CONSTRAINT RPK
		PRIMARY KEY(RefereeLicenseNo)
);

 CREATE TABLE GAME(
 	MatchID char(5) NOT NULL,
 	MatchWeek INT NOT NULL,
 	HomeTeam VARCHAR(30) NOT NULL,
 	AwayTeam VARCHAR(30) NOT NULL,
 	MDateTime DateTime NOT NULL,
 	RefID CHAR(6) NOT NULL,
 	UNIQUE(HomeTeam, MDateTime),
 	CONSTRAINT MPK
 		PRIMARY KEY(MatchID),
 	CONSTRAINT MFK
 		 FOREIGN KEY(HomeTeam) REFERENCES TEAM(TeamName)
			ON DELETE CASCADE	ON UPDATE CASCADE,
		 FOREIGN KEY(AwayTeam) REFERENCES TEAM(TeamName)
			ON DELETE CASCADE	ON UPDATE CASCADE,
		 FOREIGN KEY(RefID) REFERENCES REFEREE(RefereeLicenseNo)
			ON DELETE CASCADE	ON UPDATE CASCADE
 );

 CREATE TABLE GAME_STAT(
 	MatchID char(5) NOT NULL,
 	HomeTeamGoals INT NOT NULL,
 	AwayTeamGoals INT NOT NULL,
 	Attendance INT,
 	CONSTRAINT MSPK
 		PRIMARY KEY(MatchID),
 	CONSTRAINT MSFK
 		FOREIGN KEY(MatchID) REFERENCES GAME(MatchID)
			ON DELETE CASCADE	ON UPDATE CASCADE
 );

 CREATE TABLE BROADCASTER_INFO(
 	BroadcasterID char(6) NOT NULL, 
 	BroadcasterName VARCHAR(30) NOT NULL,
 	PRIMARY KEY(BroadcasterID)

 );
 

 CREATE TABLE REGIONAL_BROADCASTER(
 	Region VARCHAR(30) NOT NULL,
 	BroadcasterID char(6),
 	CONSTRAINT RBPK
 		PRIMARY KEY(REGION),
 	CONSTRAINT RBFK
 		FOREIGN KEY(BroadcasterID) REFERENCES BROADCASTER_INFO(BroadcasterID)
			ON DELETE SET NULL	ON UPDATE CASCADE
 );